### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [Anonychun/Wifi-Chun#2]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by Anonychun** [comment]
Hi sir, thank you for your contribution, I will be happy to receive it.

**Comment by mansya** [comment]
hi sir. I have completed the design for this project. How ? do you like it ? if yes which one do you like?
![Wifi Chun](https://user-images.githubusercontent.com/33461607/61057878-55fc0800-a420-11e9-9bf4-1908c1eb8ef0.png)

**Comment by mansya** [comment]
hi sir how about this offer? can it continue?
